parameters:
    env(APP_LOCALE): en
    locale: '%env(resolve:APP_LOCALE)%'
    env(MEMCACHED_DSN): 'memcached://localhost:11211'

framework:
    ide: 'phpstorm://open?file=%%f&line=%%l'
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.memcached
                provider: "%env(MEMCACHED_DSN)%"
            doctrine.system_cache_pool:
                adapter: cache.adapter.memcached
                provider: "%env(MEMCACHED_DSN)%"
    esi: { enabled: true }
    translator:
        fallbacks: ["%locale%"]
        logging: false
    secret: "%env(APP_SECRET)%"
    router:
        strict_requirements: ~
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: false }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    fragments: { path: /_fragment }
    http_method_override: true
