services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $swpDomain: '%env(SWP_DOMAIN)%'

    SWP\Bundle\MultiTenancyBundle\Command\:
        resource: '../../Command/*'

    SWP\Bundle\MultiTenancyBundle\Command\GetPublicSuffixListCommand:
        bind:
            $suffixListEndpoint: '%env(PUBLIC_SUFFIX_LIST_ENDPOINT)%'
            $suffixListFilename: '%env(PUBLIC_SUFFIX_LIST_FILENAME)%'
        arguments:
            - '@service_container'
